### ISSUE TITLE
Blog like/unlike request not working properly

### ISSUE THREAD

**Issue by hasancomce** [freedomcombination/monorepo#1024]
When the like/unlike button is clicked repeatedly, it sends the same request. It should work in the `like/unlike` loop. 

According to the response after the blog like/unlike request, the blog in the context may not be updated. 

Request 1: 
<img width="841" alt="1" src="https://github.com/wsvvrijheid/monorepo/assets/79446497/a9a950b9-209e-4fae-aa54-fd045e60cbbe">

Request 2: 
<img width="841" alt="2" src="https://github.com/wsvvrijheid/monorepo/assets/79446497/90724ded-a312-4eab-a7c5-63238b688d28">

Request 3: 
<img width="841" alt="3" src="https://github.com/wsvvrijheid/monorepo/assets/79446497/3cbc1773-75b3-4de9-8296-fd7001574a80">

**Comment by burakndrlnd** [comment]
![image](https://github.com/freedomcombination/monorepo/assets/154612391/f7736bd0-9582-4f62-a442-650af0b3f7f8)

@7alip this is how console look like after i click like button. im unregistered user. i think public user role has no permission those endpoints.

**Comment by burakndrlnd** [comment]
I was not running it on local. It was freedomcombination.com

**Comment by 7alip** [comment]
> I was not running it on local. It was freedomcombination.com

If you click the button repeatedly, recaptcha validation may reject your request. We implemented this intentionally to prevent bots from liking or disliking the content.
