### ISSUE TITLE
Use Instagram Basic API for TrendRights homepage

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1088]
https://developers.facebook.com/docs/instagram-basic-display-api/

We would like to display social media timelines for [trendrights](https://www.instagram.com/trendrights) instagram account (or maybe for all platforms).

This task is just an investigation of getting data from Instagram API.

<image src="https://github.com/freedomcombination/monorepo/assets/22167684/d8d9bd0d-4dbe-470f-8c06-e75af0aabe0f" width="300" />

**Comment by bbluechip** [comment]
Can I get more detailed information and step by step guide about this task

**Comment by 7alip** [comment]
> Can I get more detailed information and step by step guide about this task

@bbluechip This task is just an investigation task and we will create follow up tasks for components.

**Comment by ertugrul-aydin** [comment]
To complete this tak, i need to access the social media hub through Fb Developers and follow the necessary stept to integrate the instagram Api
