### ISSUE TITLE
Maximum call stack size exceeded at https://www.freedomcombination.com/tr/activities

### ISSUE THREAD

**Issue by burakndrlnd** [freedomcombination/monorepo#1098]
![image](https://github.com/freedomcombination/monorepo/assets/154612391/9e6c5312-6c3d-4fb4-b3d9-e5b4a4377c37)
image belongs to local server.

but it happens at https://www.freedomcombination.com/tr/activities too. just click adress and scroll to bottom. and make some ups and downs.
![image](https://github.com/freedomcombination/monorepo/assets/154612391/5830d33b-b969-4fb7-9c59-2b3895b884a9)

**Comment by 7alip** [comment]
@burakndrlnd I had to reduce framer-motion version
