### ISSUE TITLE
Blog edit form content is not visible

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1307]
### Describe the bug

<img width="1760" alt="blog-edit-form" src="https://github.com/freedomcombination/monorepo/assets/22167684/8b495f9c-8b46-47aa-84e6-190b19717548">

**Comment by ertugrul-aydin** [comment]
When query the blog endpoint with an ID, the response returns null, whereas other endpoints like hashtag and profile correctly return data for the same request structure. Everything appears to be configured properly. Any suggestions on what might be causing this issue?


![code](https://github.com/freedomcombination/monorepo/assets/48697010/e854245e-f558-43be-87a8-7986de2c4edf)
