### ISSUE TITLE
Send email to admins when a new volunteer application is created

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [freedomcombination/monorepo#1316]
### Is your feature request related to a problem? Please describe.

After volunteers have applied, send two separate emails: one to the volunteer and one to the admins.

### Describe the solution you'd like

Adjust `create` controller or use `afterCreate` lifecycle. The difference is, `afterCreate` will run even when the data is created from Strapi dashboard.

The roles that should receive information emails include `admin` and `human-resource`. Send an email to each user in these roles.

**Comment by 7alip** [comment]
Take this task after #1271 and #1330 are merged
