### ISSUE TITLE
ObservationForm Send button is not visible on mobile

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [freedomcombination/monorepo#1317]
### Describe the bug

The `Send` button of the ObservationForm is not visible in mobile devices.

### To Reproduce

1. Go to "/profiles"
2. Click on a profile row
3. Scroll down to Observations section underneath the form
4. See that Send button is not visible on mobile

### Screenshots

![image](https://github.com/freedomcombination/monorepo/assets/58182269/fe8d82e2-3f49-40e8-88b5-3eb3fc9623d7)

**Comment by 7alip** [comment]
@bbluechip Will you continue working on this task, then remember moving it to In progress. Otherwise you can unassign yourself or pick another one if you want.
