### ISSUE TITLE
Extend User Statistics with New Fields

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1320]
### Is your feature request related to a problem? Please describe.

We keep some user statistics weekly. We've added new tables like ArchiveContent and ArchiveImage. These fields must be included in statistics as well.

### Describe the solution you'd like

New fields: `ArchiveContent`, `ArchiveImage`, `Observation`, `Assets`, `AssetsTracking`

- [ ] Add new fields to the cron job `apps/api/config/cron/userStats.ts` (check getStast function)
- [ ] Add new fields to  `UserStatsData` type in `user-stats.ts`

**Comment by MustafaTRKYLMZ** [comment]
> ### Is your feature request related to a problem? Please describe.
> We keep some user statistics weekly. We've added new tables like ArchiveContent and ArchiveImage. These fields must be included in statistics as well.
> 
> ### Describe the solution you'd like
> New fields: `ArchiveContent` and `ArchiveImage`
> 
> * [ ]  Add new fields to the cron job `apps/api/config/cron/userStats.ts` (check getStast function)
> * [ ]  Add new fields to  `UserStatsData` type in `user-stats.ts`

Did we add observation, assets and about profile new futures?

**Comment by 7alip** [comment]
@MustafaTRKYLMZ Observation and assets can be created only by admins and some specific roles. That's why I didn't consider including them. We can include them too if you want

**Comment by MustafaTRKYLMZ** [comment]
> @MustafaTRKYLMZ Observation and assets can be created only by admins and some specific roles. That's why I didn't consider including them. We can include them too if you want

I think well. Because almost 6 people have HR role. It means They have to create obsevation for each profile, after they met somebody.

**Comment by 7alip** [comment]
We will probably remove UserStatistics model as we are planning to implement AuditLogs in https://github.com/freedomcombination/monorepo/tree/feat/logs
