### ISSUE TITLE
Add custom error page

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1340]
### Is your feature request related to a problem? Please describe.

<img width="400" alt="Screenshot 2024-05-22 at 13 37 28" src="https://github.com/freedomcombination/monorepo/assets/22167684/b14361c9-c0e5-46df-aca2-e2fd142e7887">

Currently we see the default error page without layout/menu.

### Describe the solution you'd like

https://nextjs.org/docs/pages/building-your-application/routing/custom-error

**Comment by myniqx** [comment]
@7alip it seems it has already done.
