### ISSUE TITLE
Volunteer form error handling

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [freedomcombination/monorepo#1342]
### Describe the bug

When person is already volunteered but again trying to volunteer, now we are saying error.description. It should be "you are already applied for being volunteering"

### To Reproduce

1. Go to 'https://www.freedomcombination.com/join'
2. Click on 'submit'
4. If you are already applied, See error

### Device

- Device: [e.g. iOS, iPhone6]
- OS: [e.g. Windows11]

**Comment by 7alip** [comment]
@MustafaTRKYLMZ Is this necessary as https://github.com/freedomcombination/monorepo/issues/1341 should fix the issue?

**Comment by MustafaTRKYLMZ** [comment]
> @MustafaTRKYLMZ Is this necessary as #1341 should fix the issue?

1341 is about register  But same error, there is in the volunteer form. 

Some person trying to be volunteer second time.
