### ISSUE TITLE
Fix hashtag edit form zoned date field

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1365]
### Describe the bug

When you update any hashtag field, the date field gets updated probably because of time zone.

### To Reproduce

<img width="1284" alt="Screenshot 2024-05-29 at 20 58 13" src="https://github.com/freedomcombination/monorepo/assets/22167684/67417bbc-420a-4125-94a8-3519010d4f7e">

**Comment by ertugrul-aydin** [comment]
@7alip  After editing the hashtags locally, I observed that the date did not change. You can see this in the screenshots below. I couldn't pinpoint the exact cause of the problem.

![Image](https://github.com/freedomcombination/monorepo/assets/48697010/062e00f3-5fdf-4012-9b95-727c66049a71)



![Image](https://github.com/freedomcombination/monorepo/assets/48697010/1bc54223-a1c1-4069-ae37-4069a3ca7d3d)

**Comment by 7alip** [comment]
You can use https://wsvv-api-staging.onrender.com as NEXT_PUBLIC_API_URL to test
