### ISSUE TITLE
Move app/mail to package/ui/src/mail

### ISSUE THREAD

**Issue by myniqx** [freedomcombination/monorepo#1432]
### Is your feature request related to a problem? Please describe.

when we design mail template, in backend, there is currently no way we can preview what we design.
if we move mail files to common folder, we can add a page to dashboard that can render mail template preview with hotrefresh

### Describe the solution you'd like

move all the files inside of app/mail (except index.tsx) to package/ui/src/mail
then create a page in dashboard, list all that templates in a menu.
when user select a template, in same page show template how it looks like.
this page can be shown only development mode.

### Describe alternatives you've considered

i dont know is storybook capable of showing react mail components, this can be an alternative. (but i cant even run storybook in my windows 11 properly)

**Comment by 7alip** [comment]
@myniqx You should be able to see email components when you run the following commands:

```
cd apps/api && yarn email
// localhost:3000
```

<img width="1753" alt="Screenshot 2024-06-15 at 23 29 22" src="https://github.com/freedomcombination/monorepo/assets/22167684/8f320a63-ec89-4471-a1fa-aebfcf42e11e">

**Comment by myniqx** [comment]
😅
