### ISSUE TITLE
Strapi automatically rotates vertical images.

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1444]

**Comment by SelimEmre** [comment]
Could you please add some details for this issue? How can we reproduce this issue?

**Comment by 7alip** [comment]
I noticed auto orientation setting in Strapi dashboard and enable it. Hopefully it can fix the issue. We can reopen it if someone reports it again.

<img width="2027" alt="Screenshot 2024-08-07 at 09 56 50" src="https://github.com/user-attachments/assets/c5e9e3d0-5f03-4afc-b884-c3b99f0bf7c3">
