### ISSUE TITLE
TEST: Contact Form

### ISSUE THREAD

**Issue by ulgerf** [freedomcombination/monorepo#1654]
**Test Case ID:** TC00?

Title: Sending a Message After Filling Required Fields

Description: The user should not receive an error message after filling in the required fields and sending the message.

**Steps:**

Fill in the required fields.
Send the message.
**Expected Result:** No error message should appear.

**Actual Result:** [Enter the result here]

** Test Case**

**Comment by 7alip** [comment]
@MustafaBudak41 @ulgerf Can we close if it's done

**Comment by MustafaBudak41** [comment]
Finish
