### ISSUE TITLE
FIX:  Password Reset Email Not Sent & No Warning for Non-Existent Email

### ISSUE THREAD

**Issue by ulgerf** [freedomcombination/monorepo#1827]
**> Issue 1:** After submitting a valid email for password reset, no reset email is received. This indicates that the password reset email function is not working as expected.
**>Issue 2:** When entering a non-existent email during the password reset process, there is no warning or error message indicating that the email is not in the system.

### To Reproduce

>Go to the login page.
Click on the "Forgot Password" link.
Enter a valid email address.
Click on "Submit."
**Expected Result:** A password reset email should be sent to the provided email address.
**Actual Result:** No email is received.
Repeat the process by entering a non-existent email address.
**Expected Result:** A warning should appear indicating that the email is not registered in the system.
**Actual Result:** No warning or error message is shown, and the system behaves as though the email exists.
**Severity:** High
**Priority:** Medium

**Comment by myniqx** [comment]
as the image shows, i get forget-password mail, and checked that resetPasswordToken is exist :
![image](https://github.com/user-attachments/assets/4f649015-30d1-4d72-84f8-b1aa45b4f3b6)

> Expected Result: A warning should appear indicating that the email is not registered in the system.

i think we shouldnt show other users that entered email address is registered or not. may be we can show an info that is 'if you enter a registered email we ll send an email'
what do you think ?
