### ISSUE TITLE
FIX: Chakra 3 - Styling Issues

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1839]
### Monorepo

- [x] Some colorPalette values don't apply colors, remains black (etc. gray)
- [x] All vertical Alert (with icon) components 
- [x] Check all modal sizes, some modals should have `cover` size like Dev mail modal

### Dashboard
- [x] HeaderMenuItem black border 
- [x] ModelMedia width in Create/Edit forms
- [x] Assets accordion title spacing and double arrows

**Comment by myniqx** [comment]
are those buttons expected to see like this?

![image](https://github.com/user-attachments/assets/d0bbe572-15bd-45b7-be9f-b41a6c8294d5)
![image](https://github.com/user-attachments/assets/c9904f52-afc8-4f88-8975-29d7b8cc0394)
-----
those 403 errors look like blog re-render's error. when i click that link startswith wsvv-api... it just open in another window without error. and also there are i18n errors in page.

![image](https://github.com/user-attachments/assets/d0354e0d-a238-4320-851c-04c7a7a8c198)
