### ISSUE TITLE
Try ReactEmail

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#354]
https://www.youtube.com/watch?v=MdO1AKVTkLI
https://react.email/docs/introduction

Is it possible to use ReactEmail in our Strapi backend? If not, we can still use it in the frontend in some cases.

**Comment by bllakcn** [comment]
With a quick overview, it seems it is possible to generate HTML output out of ReactEmail. This can be consumed by `sendTemplatedEmail()` in Strapi. 
Though, not sure if this can turn into an automated process as ReactEmail runs in localhost as a tool to write emails with React.

https://docs.strapi.io/dev-docs/plugins/email#using-the-sendtemplatedemail-function
https://react.email/docs/utilities/render#3-convert-to-html
