### ISSUE TITLE
Art comments are not being displayed

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#541]
@MustafaTRKYLMZ Is there a verification procedure in place that blocks a submitted comment from being displayed? I don't see my comment after submit it in art detail page. Would editors approve the comments for them to be displayed on the page? If not, there seems a bug. We may be saving the comments as draft or something else is going wrong.

- Add additional prop (isBrowser: boolean or whatever) to session once user visits the page (checkAuth => /api/auth/user)
- Create `api/comment` api route
- Require session has `isBrowser` to pass TOKEN

**Comment by bllakcn** [comment]
We can utilize Google reCaptcha v3 to secure the public comment section against bots.
[react-google-recaptcha](https://www.npmjs.com/package/react-google-recaptcha)

**Comment by 7alip** [comment]
@MustafaTRKYLMZ Can we create a site key from https://www.google.com/recaptcha/admin/create? (https://developers.google.com/recaptcha/docs/v3)
