### ISSUE TITLE
Update foundation social buttons in footer (instagram-linkedin)

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#885]
https://twitter.com/freedomcombin
https://www.linkedin.com/company/freedom-combination
https://www.youtube.com/@FreedomCombination

There is no instagram I think

**Comment by burakndrlnd** [comment]
@7alip can i have social media adresses ?

**Comment by 7alip** [comment]
> @7alip can i have social media adresses ?

@burakndrlnd I updated the description
